# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 758fe22c238a09259104548085d3ef85d672e450b884b8c92548a095bf035503b6819927d098c5a57ac66f46d48907f104f65657c84dcb021b5ebeb85f8ac4ab

test:
  secret_key_base: e25c5d01d64bdb0deb606f20addfdf31b2ff6486f67933ea26c0280df304cf4029067e1a70cc058f9847d2041edea361f4ff925eb0ee9859d90bb08c0fe2e479

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
